"""add create_at

Revision ID: 81f8be8181e6
Revises: bc3b8ae7c09f
Create Date: 2026-03-08 23:47:30.876725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81f8be8181e6'
down_revision: Union[str, Sequence[str], None] = 'bc3b8ae7c09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'created_at')
    # ### end Alembic commands ###
